### ISSUE TITLE
dns perf not running 

### ISSUE THREAD

**Issue by mehmood-007** [cobblau/dnsperf#4]
I'm not able to run dns perf, 

I am running the following command :
# ./dnsperf -d a.out -s 161.202.149.4

but nothing appears in the output :
DNS Performance Testing Tool
[Status] Processing query data
----Nothings appears 

Please guide me in this regard

**Comment by cobblau** [comment]
Hi @mehmood-007,
Sorry for replying so late.
Which linux release version did you used when run the test below?

**Comment by cobblau** [comment]
I Just fixed this bug. Please checkout the 'master' branch and try your testing again.
Tell me whether your testing passed. Thank you very much.

**Comment by jiashengzhang** [comment]
Thanks cobblau, The new code can run in my environment perfectly!

**Comment by cobblau** [comment]
Enjoy!
